FROM openjdk:11-jdk-slim

RUN apt-get update
RUN apt-get install -y git

ENV RDS_HOSTNAME=localhost
ENV RDS_PORT=3306
ENV RDS_DB_NAME=blogdb
ENV RDS_USERNAME=ssar
ENV RDS_PASSWORD=ssar1234

WORKDIR /home/ubuntu/

COPY ./entrypoint.sh ./entrypoint.sh

ENTRYPOINT ["./entrypoint.sh"]

EXPOSE 8080