FROM ubuntu

RUN apt-get update
RUN apt-get install -y git
RUN apt-get install -y openjdk-11-jdk
RUN apt-get install -y mariadb-server

COPY my.cnf /etc/mysql/
ADD  init.sql /docker-entrypoint-initdb.d

WORKDIR /home/ubuntu/
COPY ./run.sh ./run.sh

ENTRYPOINT ["mysqld"]
ENTRYPOINT ["./run.sh"]


EXPOSE 3306
EXPOSE 8080